version: "3"
services:
    app:
        build:
            context: ./
            dockerfile: dockerfiles/app/Dockerfile
        volumes:            
            - "./:/var/www"
        links:
          - redis
        ports:
          - "80:81"
          - "5173:5173"
    redis:
      image: redis:5.0